collections:
  jobs:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /blog/:year/:title:output_ext
feed:
  excerpt_only: true
  path: /blog/feed.xml
plugins:
  - jekyll-feed
source: ./src
