name: "Project triage: Issues"

on:
  issues:
    types: [opened, transferred]

jobs:
  add-to-project-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/compilerla/projects/${{ vars.GH_PROJECT }}
          github-token: ${{ secrets.GH_PROJECTS_TOKEN }}
